Packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(dtplyr)
```


Sample data frame
```{r}
sample_dates <- data.frame(sample = c("CAL_S2", "CAL1", "CAL2", "CAL3"),
                           date = c(ymd("2021-11-15"), ymd("2021-08-16"), ymd("2021-09-21"), ymd("2021-10-26")),
                           phase = c("IV", "III", "IV", "IV"),
                           ave_carb = c("IV (0.29)", "III (0)", "IV (0.75)", "IV (0.47)"))
sample_dates$ave_carb <- factor(sample_dates$ave_carb, levels = c("III (0)", "IV (0.75)", "IV (0.47)", "IV (0.29)"))

```

Reference file and annotations
```{r}
ref <- fread("/projects/b1052/mckenna/resources/diamond/glycerol_kinase_uniprotkb.tsv", sep = "\t")
colnames(ref) <- c("entry", "entry_name", "protein_names", "gene_names", "organism", "gene_length", "reviewed")
ref <- ref %>%
  select(-reviewed)

df <- fread("./results/diamond_contigs/uniprot_glycerol.tsv", col.names = c("qseqid", "sseqid", "pident", "length", "mismatch",
                                                                          "gapopen", "qstart", "qend", "sstart", "send",
                                                                          "evalue", "bitscore")) %>%
  separate_wider_delim("sseqid", "|", names = c("tr", "entry", "entry_name")) %>%
  select(-c(tr, entry_name)) %>%
  separate_wider_regex("qseqid", c(contig = ".*", "_", num_on_contig = ".*")) %>%
  filter(pident >= 70) %>%
  left_join(ref, by = "entry")

rm(ref)

```


Get depth by sample - read in rpkm file and join to ref+annotation df
```{r}
get_depth_by_sample <- function(sample){
  depth_file <- paste0("./results/pileup/", sample, "/", sample, ".rpkm.txt")
  depth <- read.table(depth_file, comment.char = "#", 
                         col.names = c("contig", "length", "bases", "coverage", "reads", "rpkm", "frags", "fpkm")) %>%
    select(-c(length, bases, frags, fpkm))
  df_with_depth <- left_join(df, depth, by = "contig")
  return(df_with_depth)
}


depth_list_all <- lapply(setNames(sample_dates$sample, sample_dates$sample), get_depth_by_sample)

saveRDS(depth_list_all, "./notebooks/data_files/depth_list_all_glycerol.RDS")

# Return a single df and delete preceding files
depth_all <- bind_rows(depth_list_all, .id = "sample")

rm(depth_list_all, df)

```


Cleaning
```{r}
depth_list_all <- readRDS("./notebooks/data_files/depth_list_all_glycerol.RDS")
depth_all <- bind_rows(depth_list_all, .id = "sample")
rm(depth_list_all, df)

glycerokinase <- depth_all %>%
  filter(str_detect(protein_names, "EC 2.7.1.30")) %>%
  group_by(sample, organism) %>%
  summarise(sum_rpkm = sum(rpkm)) %>%
  left_join(sample_dates, by = "sample")
```

```{r}
glycerokinase %>%
  filter(str_detect(organism, "(?i)accumulibacter|phosphoribacter|dechloromonas|competibacter|tetrasphaera")) %>%
  mutate(organism_clean = case_when(str_detect(organism, "(?i)accumulibacter") ~ "Accumulibacter",
                                    str_detect(organism, "(?i)competibacter") ~ "Competibacter",
                                    str_detect(organism, "(?i)tetrasphaera") ~ "Tetrasphaera",
                                    str_detect(organism, "(?i)dechloromonas") ~ "Dechloromonas",
                                    str_detect(organism, "(?i)phosphoribacter") ~ "Phosphoribacter")) %>%
  mutate(organism_clean = factor(organism_clean, 
                                 levels = c("Accumulibacter", "Dechloromonas", "Phosphoribacter", "Tetrasphaera", "Competibacter"))) %>%
  ggplot(., aes( x = ave_carb, y = sum_rpkm, fill = phase)) +
  facet_wrap(~organism_clean, scales = "free") +
  geom_bar(stat = "identity") +
  theme_classic() +
  ylim(0, 8) + 
  scale_fill_manual(values = c("grey", "lightgoldenrod")) +
  labs(x = "", y = "Glycerol kinase abundance [RPKM]") +
  theme(legend.position = "none", strip.text = element_text(face = "italic"), 
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

ggsave(file.path("~/OneDrive - Northwestern University/Project folders/S2EBPR metagenomics/calumet2021/figures/glycerol_bar.png"), width = 7, height = 4, units = "in", dpi = 320)
  
```

